---
title: "Lifespan_analysis_Rachel"
author: "Nicole Riddle"
date: "2023-06-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R script to analyze Rachel's PCL data

We need to analyze Rachel's PCL block. This script will serve as template to analyze all other knockdown plots as well. 

# Setting things up
```{r}
# Cleaning up
rm(list=ls())
install.packages("here")
install.packages('hrbrthemes')
install.packages("survminer")


# Loading libraries
library(here)
library(ggplot2)
library(tidyverse)
library(hrbrthemes)
library(viridis)
library(readxl)
library(survival)
library(survminer)
library(xlsx)
```


## _________________________________________________
# New/My Stuff
```{r}
# here I am fitting my data to the survival surve with this tutorial
# https://www.sthda.com/english/wiki/survminer-r-package-survival-data-analysis-and-visualization
#install.packages("survminer")
# library(survival)
# library(survminer)
# 
# # Create the variable sex 2
# data("lung")
# lung$sex2 <- factor(lung$sex, levels = c(2, 1))
# 
# # Fit survival curves for the variable sex
# fit1<- survfit(Surv(time, status) ~ sex, data = lung)
# ggsurvplot(fit1, risk.table = TRUE)



library(dplyr)

library("survival")
library(broom)

library(xlsx)
Aplysia_lifespan_data <- read.xlsx("../../data/Aplysia_deaths.xlsx", sheetIndex = "DeathData4R")
ApDeaths <- Aplysia_lifespan_data[,c(1:6)]
ApDeaths$Diet <- factor(ApDeaths$Diet, levels = c("AL","CR"))
# ApDeaths$n <- as.integer(ApDeaths$n)
# ApDeaths$Age <- as.integer(ApDeaths$Age)

# had to manually go to my dataframe and include "status" as there is a very specific way to notate a death or no change using 1 and 0.5 respectively

fit2 <- survfit(Surv(time = Age, event = status) ~ Diet, data = ApDeaths, type = "kaplan-meier")
tidy(fit2)
summary(fit2)

library(survminer)
test <- ggsurvplot(fit2, 
           risk.table = F, 
           tables.height = 0.2, 
           tables.theme = theme_cleantable(),
           pval = T,
           surv.median.line = "hv",
           ggtheme = theme_classic(),
           legend.title="Diet",
           legend.labs = c("AL","CR"),
           linetype = c("solid", "dashed"),
           xlab = "Age (days)",
           font.x = c(14, "bold", "black"),
           font.y = c(14, "bold", "black"),
           font.tickslab = c(12,"plain","black"),
           surv.scale = "percent",
           palette = c("black", "gray58"), conf.int = F)

test2 <- test$plot +
  scale_x_continuous(expand = c(0,0,0.05,0)) +
  scale_y_continuous(expand = c(0,0,0.05,0), labels=scales::label_percent())


## below did not work to shade the months, or it did but it looked bad so I will not use it
# test2 + xlim(175, NA) +
#   annotate("rect", xmin = 181, xmax = 212, ymin = 0, ymax = 1.07, 
#            alpha = .3) + # This will give me the boxes
#   annotate("rect", xmin = 242, xmax = 273, ymin = 0, ymax = 1.07, 
#            alpha = .3) +
#   annotate("rect", xmin = 303, xmax = 334, ymin = 0, ymax = 1.07, 
#            alpha = .3)+
#   annotate("rect", xmin = 365, xmax = 394, ymin = 0, ymax = 1.07, 
#            alpha = .3) +
#   annotate(geom = "text", x = 197, y = 1.035, label="Month 6")+
#   annotate(geom = "text", x = 227, y = 1.035, label="Month 7")+
#   annotate(geom = "text", x = 258, y = 1.035, label="Month 8")+
#   annotate(geom = "text", x = 288, y = 1.035, label="Month 9")+
#   annotate(geom = "text", x = 318, y = 1.035, label="Month 10")+
#   annotate(geom = "text", x = 350, y = 1.035, label="Month 11")+
#   annotate(geom = "text", x = 379, y = 1.035, label="Month 12")

```

