---
title: "MakingOrg.Db"
output: html_document
date: "2025-01-13"
---

```{r}
library(dplyr)
library(tximport)
library(DESeq2)
library(ggplot2)
library(sva)
library(pheatmap) # for hierarchical clustering
library(purrr) # for "set_names()"
library(tibble)
library(ggVennDiagram)
library(UpSetR)
library(GenomicFeatures)
library(devtools) # for making the Org.db
library(AnnotationForge)
library(robustbase) # needed for rrcov
library(rrcov) # for statistically testing for outliers in PCA
library(stringr) # for str_detect to filter metadata
library(xlsx)
```

### making an Org.db
```{r}
# I want to make an Org.db for this species to use in GO
devtools::install_version("dbplyr", version = "2.3.4")
library(dbplyr)
packageVersion("dbplyr")
# after you check to make sure the correct dbplyr version is installed you need to restart R to use it

## first will need to run the below code so that you do not encounter a connection problem with Ensemble then the AnnotationForge should work well
httr::set_config(httr::config(ssl_verifypeer = FALSE))
## Species: Aplysia californica
makeOrgPackageFromNCBI(version = "0.1",
                       author = "EC Randolph <erandolp@uab.edu>",
                       maintainer = "EC Randolph <erandolp@uab.edu>",
                       outputDir = "../../data/Org.dbs/",
                       tax_id = "6500",
                       genus = "Aplysia",
                       species = "californica",
                       rebuildCache = F)
```


